/****************************************************************************
 *																								 	 *
 * Data file for datafile.s															 	 *
 * The #defines below correspond to	files in datafile.s				 		    *
 *																						 		    *
 ****************************************************************************/


enum
	{
	LOADPIC,
	FRONTEND_TEX,
	FRONTEND_SAN,
	FRONTEND_TED,
	PLAYER_TEST_SKD,
	PLAYER_TEXTURES,
	PLAYER_EDIT_PAL_BANK,
	PLAYER_EDIT_NUMS,
	KIT_TEXTURES,
	KIT_PALS,
	SFXDAT,
	FRONTVBS,
	FRONTDAT,
	FRONTVBS2,
	FRONTDAT2,
	LOADMAN_TEX,

	};

