/*********************************************
 *															* 															
 *	PSX library includes 						   * 
 *															* 															
 *********************************************/

#include <sys/types.h>
#include <sys/file.h>
#include <libspu.h>
#include <libetc.h>
#include <libgte.h>
#include <libgpu.h>
#include <libgs.h>
#include <libsn.h>
#include <libcd.h>
#include <kernel.h>
#include	"ctrller.h"
#include <stdarg.h>
#include <stddef.h>
#include <libsnd.h>
#include <libpress.h>
#include <libapi.h>
#include <libmcrd.h>

#include <strings.h>
#include <inline_c.h>
#include <gtemac.h>

//#include <libmath.h>
//#include <libcomb.h>



