/*****************************************
 *
 * Flag nums
 *
 ******************************************/

BYTE ts_club_teams_list[MAX_CLUB_TEAMS]={

AC_Milan,
AFC_Ajax,
Arsenal,
AS_Monaco,
Aston_Villa,
Bayer_04_Leverkusen,
Borussia_Dortmund,
Brondby_IF,
Celta_de_Vigo,
Celtic,
Chelsea,
Club_Atletico_de_Madrid,
Club_Brugge_KV,
Dynamo_Kyiv,
FC_Barcelona,
FC_Bayern_Munchen,
FC_Girondins_de_Bordeaux,
FC_Porto,
FC_Steaua_Bucuresti,
Feyenoord,
Fiorentina,
Galatasaray_SK,
Grasshopper_Club,
IFK_Goteborg,
Internazionale,
Juventus,
Kaiserslautern,
Liverpool,
Manchester_Utd,
NK_Croatia_Zagreb,
Olympique_de_Marseille,
Olympique_Lyonnais,
Panathinaikos,
Paris_Saint_Germain,
Parma,
PSV_Eindhoven,
Rangers,
Real_Madrid_CF,
Rosenborg_BK,
RSC_Anderlecht,
SK_Rapid_Wien,
SL_Benfica,
Sporting_Clube_de_Portugal,
SV_Werder_Bremen                 

};

BYTE ts_country_teams_list[MAX_LANGS][MAX_COUNTRY_TEAMS + MAX_USER_TEAMS]={

//*** Team flags in English alphbetical order **

	Albania,
	Andorra,				
	Argentina,				
	Armenia,				
	Australia,
	Austria,				
	Azerbaijan,
	Belarus,				
	Belgium,				
	Bosnia,					
	Brazil,					
	Bulgaria,				
	Cameroon,				
	Canada,					
	Chile,					
	Colombia,				
	Croatia,				
	Cyprus,				 	
	Czech_Republic,		
	Denmark,				
	Egypt,			  		
	England,		  		
	Estonia,		  		
	Faroe_Islands,
	Finland,
	France,		  		 	
	Georgia,		  		
	Germany,		  		
	Greece,		  		 	
	Hungary,		  		
	Iceland,		  		
	India,         		
	Iran,			  		
	Israel,		  		 	
	Italy,			  		
	Jamaica,		  		
	Japan,			  		
	Korean_Republic,
	Latvia,		  		 	
	Liechtenstein, 		
	Lithuania,	  		 	
	Luxembourg,	  		
	Macedonia,	  		 	
	Malta,			  		
	Mexico,		  		 	
	Moldova,		  		
	Morocco,		  		
	Netherlands,	  		
	New_Zealand,	  		
	Nigeria,		  		
	Northern_Ireland,   
	Norway,		  		 	
	Pakistan,		  		
	Paraguay,		  		
	Poland,		  		 	
	Portugal,		  		
	Republic_of_Ireland,
	Romania,      		
	Russia,		 		 	
	San_Marino,	 		
	Saudi_Arabia, 		
	Scotland,     		
	Slovakia,				
	Slovenia,		 		
	South_Africa, 		
	Spain,			 		
	Sweden,		 		 	
	Switzerland,	 		
	Tunisia,		 		
	Turkey,		 		 	
	Ukraine,		 		
	United_States,		
	Wales,        		
	Yugoslavia,
	User_teams_start+0,
	User_teams_start+1,
	User_teams_start+2,
	User_teams_start+3,
	User_teams_start+4,
	User_teams_start+5,
	User_teams_start+6,
	User_teams_start+7,



/*** Team flags in French alphbetical order **/

	Canada,
	Albania,
	Andorra,				
	Argentina,				
	Armenia,				
	Australia,
	Austria,				
	Azerbaijan,
	Belarus,				
	Belgium,				
	Bosnia,					
	Brazil,					
	Bulgaria,				
	Cameroon,				
	Albania,					
	Chile,					
	Colombia,				
	Croatia,				
	Cyprus,				 	
	Czech_Republic,		
	Denmark,				
	Egypt,			  		
	England,		  		
	Estonia,		  		
	Faroe_Islands,
	Finland,
	France,		  		 	
	Georgia,		  		
	Germany,		  		
	Greece,		  		 	
	Hungary,		  		
	Iceland,		  		
	India,         		
	Iran,			  		
	Israel,		  		 	
	Italy,			  		
	Jamaica,		  		
	Japan,			  		
	Korean_Republic,
	Latvia,		  		 	
	Liechtenstein, 		
	Lithuania,	  		 	
	Luxembourg,	  		
	Macedonia,	  		 	
	Mexico,		  		 	
	Moldova,		  		
	Morocco,		  		
	Netherlands,	  		
	New_Zealand,	  		
	Nigeria,		  		
	Northern_Ireland,   
	Norway,		  		 	
	Pakistan,		  		
	Paraguay,		  		
	Poland,		  		 	
	Portugal,		  		
	Republic_of_Ireland,
	Romania,      		
	Russia,		 		 	
	San_Marino,	 		
	Saudi_Arabia, 		
	Scotland,     		
	Slovakia,				
	Slovenia,		 		
	South_Africa, 		
	Spain,			 		
	Sweden,		 		 	
	Switzerland,	 		
	Tunisia,		 		
	Turkey,		 		 	
	Ukraine,		 		
	United_States,		
	Wales,        		
	Yugoslavia,	 		
	User_teams_start+0,
	User_teams_start+1,
	User_teams_start+2,
	User_teams_start+3,
	User_teams_start+4,
	User_teams_start+5,
	User_teams_start+6,
	User_teams_start+7,
	

/*** German **/

/*** Italy order **/

/*** Spain order **/

/*** Dutch order **/

};


BYTE territory_teams_list[][6]={
/* Europe 1: British Isles **/
	England,
	Northern_Ireland,
	Scotland,
	Wales,
	-1,-1,		

/* Europe 2: Scandanavia **/
	Denmark,
	Finland,
	Iceland,
	Norway,
	Sweden,
	-1,

/* Europe 3 **/
	England,
	France,
	Germany,
	Italy,
	Netherlands,
	Spain,

/* Americas **/
	United_States,
	Canada,
	Mexico,
	Jamaica,
	-1,
	-1,

/* Africa **/
	Nigeria,
	Cameroon,
	Egypt,
	South_Africa,
	Morocco,
	Tunisia,

/* South America **/
	Brazil,
	Argentina,
	Colombia,
	Paraguay,
	Chile,
	-1,


};


BYTE ts_euro2000_teams_list[][ TOTAL_EURO2000_FLAGS ]={
	Albania,
	Andorra,   
	Armenia,
	Austria,
	Azerbaijan,
	Belarus,
	Bosnia,
	Bulgaria,
	Croatia,
	Cyprus,
	Czech_Republic,
	Denmark,
	England,
	Estonia,
	Faroe_Islands,
	Finland,
	France,
	Germany, 
	Georgia,
	Greece,
	Hungary,
	Iceland,
	Israel,
	Italy,
	Latvia,
	Liechtenstein,
	Lithuania,
	Luxembourg,
	Macedonia,
	Malta,
	Moldova,
	Northern_Ireland,
	Norway,
	Poland,
	Portugal,
	Republic_of_Ireland,
	Romania,
	Russia,
	San_Marino,
	Scotland,
	Slovakia,
	Slovenia,
	Spain,
	Sweden,
	Switzerland,
	Turkey,
	Ukraine,
	Wales,
	Yugoslavia,


/*** Frog order ***/
	Albania,
	Andorra,   
	Armenia,
	Austria,
	Azerbaijan,
	Belarus,
	Bosnia,
	Bulgaria,
	Croatia,
	Cyprus,
	Czech_Republic,
	Denmark,
	England,
	Estonia,
	Faroe_Islands,
	Finland,
	France,
	Germany, 
	Georgia,
	Greece,
	Hungary,
	Iceland,
	Israel,
	Italy,
	Latvia,
	Liechtenstein,
	Lithuania,
	Luxembourg,
	Macedonia,
	Malta,
	Moldova,
	Northern_Ireland,
	Norway,
	Poland,
	Portugal,
	Republic_of_Ireland,
	Romania,
	Russia,
	San_Marino,
	Scotland,
	Slovakia,
	Slovenia,
	Spain,
	Sweden,
	Switzerland,
	Turkey,
	Ukraine,
	Wales,
	Yugoslavia,

	
};

BYTE euro2000_teams[9][6]={
	Italy, Belarus, Wales, Switzerland, Denmark,-1,
	Norway, Slovenia, Latvia, Georgia, Greece, Albania,
	Germany, Moldova, Northern_Ireland, Finland, Turkey, -1,
	Russia, Armenia, Iceland, Ukraine, France, Andorra,
	England, Luxembourg, Poland, Sweden, Bulgaria, -1,
	Spain, San_Marino, Cyprus, Israel, Austria, -1,
	Romania, Liechtenstein, Hungary, Slovakia, Portugal, Azerbaijan,
	Yugoslavia, Malta, Macedonia, Republic_of_Ireland, Croatia, -1,
	Scotland, Faroe_Islands, Bosnia, Lithuania, Czech_Republic, Estonia,
};

BYTE ts_eurofinal_teams_list[][ TOTAL_EUROFINAL_FLAGS ]={

	Albania,
	Andorra,   
	Armenia,
	Austria,
	Azerbaijan,
	Belarus,
	Belgium,
	Bosnia,
	Bulgaria,
	Croatia,
	Cyprus,
	Czech_Republic,
	Denmark,
	England,
	Estonia,
	Faroe_Islands,
	Finland,
	France,
	Germany, 
	Georgia,
	Greece,
	Hungary,
	Iceland,
	Israel,
	Italy,
	Latvia,
	Liechtenstein,
	Lithuania,
	Luxembourg,
	Macedonia,
	Malta,
	Moldova,
	Netherlands,
	Northern_Ireland,
	Norway,
	Poland,
	Portugal,
	Republic_of_Ireland,
	Romania,
	Russia,
	San_Marino,
	Scotland,
	Slovakia,
	Slovenia,
	Spain,
	Sweden,
	Switzerland,
	Turkey,
	Ukraine,
	Wales,
	Yugoslavia,
	
/** French alpabetical order **/
	Albania,
	Andorra,   
	Armenia,
	Austria,
	Azerbaijan,
	Belarus,
	Belgium,
	Bosnia,
	Bulgaria,
	Croatia,
	Cyprus,
	Czech_Republic,
	Denmark,
	England,
	Estonia,
	Faroe_Islands,
	Finland,
	France,
	Germany, 
	Georgia,
	Greece,
	Hungary,
	Iceland,
	Israel,
	Italy,
	Latvia,
	Liechtenstein,
	Lithuania,
	Luxembourg,
	Macedonia,
	Malta,
	Moldova,
	Netherlands,
	Northern_Ireland,
	Norway,
	Poland,
	Portugal,
	Republic_of_Ireland,
	Romania,
	Russia,
	San_Marino,
	Scotland,
	Slovakia,
	Slovenia,
	Spain,
	Sweden,
	Switzerland,
	Turkey,
	Ukraine,
	Wales,
	Yugoslavia,

/** German order **/

/** Italian order **/

/** Spanish order **/	

/** Dutch order **/
};

BYTE worldcup_group_teams[8][4]={
	Brazil,
	Scotland,
	Norway,
	Morocco,

	Cameroon,
	Austria,
	Italy,
	Chile,

	Denmark,
	Saudi_Arabia,
	France,
	South_Africa,

	Paraguay,
	Bulgaria,
	Nigeria,
	Spain,

	Netherlands,
	Belgium,
	Korean_Republic,
	Mexico,

	Yugoslavia,
	Iran,
	Germany,
	United_States,

	Romania,
	Colombia,
	England,
	Tunisia,

	Jamaica,
	Croatia,
	Argentina,
	Japan
};


BYTE worldcup_fixlist[48][2]={
	
	Brazil, Scotland,
	Morocco, Norway,
	Italy, Cameroon,
	Cameroon, Austria,
	Saudi_Arabia, Denmark,
	France, South_Africa,
	Paraguay, Bulgaria,
	Korean_Republic, Mexico,
	Netherlands, Belgium,
	Spain, Nigeria,
	Argentina, Japan,
	Yugoslavia, Iran,
	Jamaica, Croatia,
	England, Tunisia,
	Romania, Colombia,
	Germany, United_States,
	Scotland, Norway,
	Brazil, Morocco,
	Chile, Austria,
	Italy, Cameroon,
	South_Africa, Denmark,
	France, Saudi_Arabia,
	Nigeria,Bulgaria,
	Spain, Paraguay,
	Japan, Croatia,
	Belgium, Mexico,
	Netherlands, Korean_Republic,
	Germany, Yugoslavia,
	Argentina, Jamaica,
	United_States, Iran,
	Colombia, Tunisia,
	Romania, England,
	Chile, Cameroon,
	Italy, Austria,
	Brazil, Norway,
	Scotland, Morocco,
	South_Africa, Saudi_Arabia,
	France, Denmark,
	Nigeria, Paraguay,
	Spain, Bulgaria,
	Belgium, Korean_Republic,
	Netherlands, Mexico,
	Germany, Iran,
	United_States,Yugoslavia,
	Japan, Jamaica,
	Argentina, Croatia,
	Romania, Tunisia,
	Colombia, England
};

