/***************************************************************************/
/*	psx library includes 																			*/
/***************************************************************************/
#include <sys\types.h>
#include	<sys\file.h>
#include <libspu.h>
#include <libetc.h>
#include <libgte.h>
#include <libgpu.h>
#include	<libgs.h>
#include <libsn.h>
#include <libcd.h>
#include <kernel.h>
#include <stdarg.h>
#include <libsnd.h>
#include <libpress.h>
//#include <libapi.h>
#include	<inline_c.h>
#include	<gtemac.h>
#include	<libgte.h>
#include	"include\ctrller.h"


#include "defs.c"
#include "structs.c"

#include "include\pad.h"
#include "include\mem.h"
#include "include\io.h"
//#include "include\link.h"
#include "include\draw.h"
#include "include\camera.h"
#include	"include\time.h"
#include	"include\object.h"
#include	"include\main.h"
#include	"include\genasm.h"
#include	"include\lsel.h"

