void calc_ko_draws_to_do();
void init_knockout_data();
void init_league_draw();
WORD do_league_draw();
void do_knockout_draw();
WORD calculate_winner();
void simulate_game_winner();
void calc_league_stats();
void init_worldcup_draw();
WORD do_worldcup_draw();
void do_worldcup_knockout_draw();

void ko_calc_results();

void init_euro2000_draw();
WORD check_human_territory_winner();
WORD do_euro2000_draw();



void replay_euro2000();
void calc_euro2000_2nd_place();
void add_ko_teams_to_euro_final();

