/****************************************************************************
 *																								 	 *
 * Data file for datafile.s															 	 *
 * The #defines below correspond to	files in datafile.s				 		    *
 *																						 		    *
 ****************************************************************************/


enum
	{
	LOADSCRN_TIM,
	FRONTEND_TEX,
	FRONTEND_SAN,
	FRONTEND_TED,
	PLAYER_TEST_SKD,
	PLAYER_TEXTURES,
	PLAYER_EDIT_PAL_BANK,
	BALL_BOUNCE_MDT,
	PAD_SDT,
	TBAR_OUT_MDT,
	PLAYER_EDIT_NUMS,
	KIT_TEXTURES,
	KIT_PALS,
	LANG_TEXTS_PAK,
	TITLE_SAN,
	TITLE_TEX,
	SFXDAT,
	FRONTVBS,
	FRONTDAT,
	FRONTVBS2,
	FRONTDAT2,
	TITLE_PLAYER,
	};

