	public	on

***************************************************************
*	fast variables	( dcache ) 	  		       *
***************************************************************
	section	rapid


scene_envmap_u0 dsh 1
scene_envmap_v0 dsh 1
;scene_envmap_vshift dsh 1


****************************************************************
*	fast Svectors						*
****************************************************************

* 1 sh = 1 word *
dcache_stack_overflow	dsh	1

	public	off
