void init_player_edit();
void update_player_edit();
void kill_player_edit();
void init_player_edit_once();
void init_player_edit_bootup();
void init_all_players_data();




void init_team_edit_bootup();
void init_team_edit_once();
void init_team_edit();
void update_team_edit();
void kill_team_edit();
void team_edit();

void setup_user_home_team();
void setup_user_away_team();

void update_away_team_tv_kit();
void update_home_team_tv_kit();



